---
- name: 予備機用transportファイルをコピー
  ansible.builtin.copy:
    src: /etc/postfix/transport_yobi
    dest: /etc/postfix/transport
    remote_src: true
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: postmapでDBファイルを更新
  ansible.builtin.command:
    cmd: postmap /etc/postfix/transport
  changed_when: true

- name: postfixをリロード
  ansible.builtin.service:
    name: postfix
    state: reloaded
